//sqls package is autogenerated by gosql.
//Do not edit this file.
//Changes will be lost on next auto-generate.
package sqls

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
)

var _jsonsqls map[string]string

type Statement struct {
	ReadOnly  bool
	SQL       string
}

func fatal(msg ...string) {
	fmt.Println(msg)
	os.Exit(1)
}

//LoadSQLs load sql into map from json file generated by gosql
func LoadSQLs(f string) {
	file, err := os.Open(f)
	if err != nil {
		fatal("error reading file ", f, " ", err.Error())
	}
	defer file.Close()

	byteValue, err := ioutil.ReadAll(file)
	if err != nil {
		fatal("read failure ", err.Error())
	}

	err = json.Unmarshal([]byte(byteValue), &_jsonsqls)
	if err != nil {
		fatal("parse failure ", err.Error())
	}
}

func parseStmt(s string) Statement {
	stmt := Statement{}
	ro := s[:1]
	if ro == "T" {
		stmt.ReadOnly = true
	}
	stmt.SQL = s[2:len(s)]
	return stmt
}

//Creates new user.
//
//Fields: 2, Parameters: 2
//
//  Fields: id, name
//
//  ParamFields: id, name
//
//  ReturningFields: id
//SQL:
//  insert into dbusers(id, name) values($1, $2) returning id;
func UserCreate() Statement {
	sql, ok := _jsonsqls["UserCreate"]
	if !ok {
		return Statement{}
	}
	return parseStmt(sql)
}

//Update existing user by id.
//
//Fields: 1, Parameters: 2
//
//  Fields: name
//
//  ParamFields: name, id
//SQL:
//  update dbusers set name=$1 where (id=$2);
func UserUpdate() Statement {
	sql, ok := _jsonsqls["UserUpdate"]
	if !ok {
		return Statement{}
	}
	return parseStmt(sql)
}

//Delete a user by id.
//
//Fields: 0, Parameters: 1
//
//  ParamFields: id
//SQL:
//  delete from dbusers where (id=$1);
func UserDelete() Statement {
	sql, ok := _jsonsqls["UserDelete"]
	if !ok {
		return Statement{}
	}
	return parseStmt(sql)
}

//List all users.
//
//Fields: 3, Parameters: 0
//
//  Fields: id, name, rowcount
//SQL:
//  select id, name, count(*) over() as rowcount from dbusers;
func UserListAll() Statement {
	sql, ok := _jsonsqls["UserListAll"]
	if !ok {
		return Statement{}
	}
	return parseStmt(sql)
}

